[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://webrtc-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws"
  to = "wss://webrtc-backend.onrender.com/ws"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200